.dashWebsocketComponent_js_metadata <- function() {
deps_metadata <- list(`dash_websocket_component` = structure(list(name = "dash_websocket_component",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashWebsocketComponent.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashWebsocketComponent",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_websocket_component` = structure(list(name = "dash_websocket_component",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashWebsocketComponent.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashWebsocketComponent",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_websocket_component` = structure(list(name = "dash_websocket_component",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_websocket_component.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashWebsocketComponent",
all_files = FALSE), class = "html_dependency"),
`dash_websocket_component` = structure(list(name = "dash_websocket_component",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_websocket_component.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashWebsocketComponent",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
